// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module QAUSI_CLK_SUM_ONLY (
A,B,Sum,Cin,GND,Vdd );
input  A;
input  B;
output  Sum;
input  Cin;
input  GND;
input  Vdd;
wire Cin;
wire net23;
wire Vdd;
wire net15;
wire net24;
wire A;
wire B;
wire GND;
wire Sum;

nmos1v    
 NM1  ( .S( net23 ), .G( Cin ), .B( GND ), .D( Sum ) );

nmos1v    
 NM0  ( .S( net15 ), .G( A ), .B( GND ), .D( net24 ) );

pmos1v    
 PM1  ( .S( net24 ), .G( Cin ), .B( Vdd ), .D( Sum ) );

pmos1v    
 PM0  ( .S( B ), .G( A ), .B( Vdd ), .D( net24 ) );

TGATE    
 I2  ( .Vdd( Vdd ), .In( Cin ), .Sel2( net24 ), .Sel1( net23 ), .GND( GND ), .Out( Sum ) );

TGATE    
 I0  ( .Vdd( Vdd ), .In( A ), .Sel2( B ), .Sel1( net15 ), .GND( GND ), .Out( net24 ) );

INV    
 I3  ( .Vdd( Vdd ), .In( net24 ), .GND( GND ), .Out( net23 ) );

INV    
 I1  ( .Vdd( Vdd ), .In( B ), .GND( GND ), .Out( net15 ) );

endmodule

