// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module XOR (
);
wire net4;
wire net2;
wire net1;
wire net3;

pmos1v    
 PM0  ( .S( net4 ), .G( net3 ), .B( net2 ), .D( net1 ) );

endmodule

