// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module MasterTB (
);
wire net14;
wire \gnd! ;
wire net13;
wire net9;
wire net12;
wire net11;
wire net4;
wire net8;
wire net2;
wire net5;
wire net7;
wire net10;
wire net6;
wire net3;

cap    
 C0  ( .PLUS( net14 ), .MINUS( \gnd!  ) );

ABS_VAL_DETECTOR_MASTER    
 I8  ( .VDD( net2 ), .X3( net6 ), .X1( net4 ), .X0( net3 ), .T2( net11 ), .X4( net7 ), .X2( net5 ), .T3( net12 ), .X5( net8 ), .T4( net13 ), .T1( net10 ), .T0( net9 ), .OUT( net14 ), .GND( \gnd!  ) );

vdc    
 V13  ( .PLUS( net13 ), .MINUS( \gnd!  ) );

vdc    
 V12  ( .PLUS( net12 ), .MINUS( \gnd!  ) );

vdc    
 V11  ( .PLUS( net11 ), .MINUS( \gnd!  ) );

vdc    
 V10  ( .PLUS( net10 ), .MINUS( \gnd!  ) );

vdc    
 V9  ( .PLUS( net9 ), .MINUS( \gnd!  ) );

vdc    
 V8  ( .PLUS( net8 ), .MINUS( \gnd!  ) );

vdc    
 V7  ( .PLUS( net7 ), .MINUS( \gnd!  ) );

vdc    
 V6  ( .PLUS( net6 ), .MINUS( \gnd!  ) );

vdc    
 V5  ( .PLUS( net5 ), .MINUS( \gnd!  ) );

vdc    
 V4  ( .PLUS( net4 ), .MINUS( \gnd!  ) );

vdc    
 V3  ( .PLUS( net3 ), .MINUS( \gnd!  ) );

vdc    
 V14  ( .PLUS( net2 ), .MINUS( \gnd!  ) );

endmodule

