// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module TGATE (
Vdd,GND,In,Out,Sel1,Sel2 );
input  Vdd;
input  GND;
input  In;
output  Out;
input  Sel1;
input  Sel2;
wire Vdd;
wire In;
wire Sel2;
wire GND;
wire Sel1;
wire Out;

pmos1v    
 PM0  ( .S( In ), .G( Sel2 ), .B( Vdd ), .D( Out ) );

nmos1v    
 NM0  ( .S( Out ), .G( Sel1 ), .B( GND ), .D( In ) );

endmodule

