// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module TB (
);
wire net14;
wire \gnd! ;
wire net13;
wire net9;
wire net12;
wire net15;
wire net11;
wire net4;
wire net8;
wire net7;
wire net5;
wire net6;
wire net3;
wire net10;

ABS_VAL_DETECTOR_MASTER    
 I0  ( .VDD( net15 ), .X3( net6 ), .X1( net4 ), .X0( net3 ), .T2( net11 ), .X4( net7 ), .X2( net5 ), .T3( net12 ), .X5( net8 ), .T4( net13 ), .T1( net10 ), .T0( net9 ), .OUT( net14 ), .GND( \gnd!  ) );

vdc    
 V11  ( .PLUS( net13 ), .MINUS( \gnd!  ) );

vdc    
 V10  ( .PLUS( net12 ), .MINUS( \gnd!  ) );

vdc    
 V9  ( .PLUS( net11 ), .MINUS( \gnd!  ) );

vdc    
 V8  ( .PLUS( net10 ), .MINUS( \gnd!  ) );

vdc    
 V7  ( .PLUS( net9 ), .MINUS( \gnd!  ) );

vdc    
 V6  ( .PLUS( net8 ), .MINUS( \gnd!  ) );

vdc    
 V5  ( .PLUS( net7 ), .MINUS( \gnd!  ) );

vdc    
 V4  ( .PLUS( net6 ), .MINUS( \gnd!  ) );

vdc    
 V3  ( .PLUS( net5 ), .MINUS( \gnd!  ) );

vdc    
 V2  ( .PLUS( net4 ), .MINUS( \gnd!  ) );

vdc    
 V1  ( .PLUS( net3 ), .MINUS( \gnd!  ) );

vdc    
 V0  ( .PLUS( net15 ), .MINUS( \gnd!  ) );

cap    
 C0  ( .PLUS( net14 ), .MINUS( \gnd!  ) );

endmodule

