// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module ABS_VAL_DETECTOR_MASTER (
X0,GND,VDD,OUT,X1,X2,X3,X4,T0,T1,T2,T3,T4,X5 );
input  X0;
input  GND;
input  VDD;
output  OUT;
input  X1;
input  X2;
input  X3;
input  X4;
input  T0;
input  T1;
input  T2;
input  T3;
input  T4;
input  X5;
wire VDD;
wire net34;
wire X2;
wire net043;
wire net39;
wire net36;
wire T1;
wire GND;
wire OUT;
wire T0;
wire net41;
wire X0;
wire net40;
wire T2;
wire T4;
wire net46;
wire net046;
wire net37;
wire net51;
wire net43;
wire net33;
wire net44;
wire net045;
wire X3;
wire X1;
wire X4;
wire net38;
wire net35;
wire T3;
wire net044;
wire X5;
wire net42;
wire net45;

INV    
 I19  ( .Vdd( VDD ), .In( net43 ), .GND( GND ), .Out( net043 ) );

INV    
 I18  ( .Vdd( VDD ), .In( net44 ), .GND( GND ), .Out( net044 ) );

INV    
 I17  ( .Vdd( VDD ), .In( net45 ), .GND( GND ), .Out( net045 ) );

INV    
 I16  ( .Vdd( VDD ), .In( net46 ), .GND( GND ), .Out( net046 ) );

INV    
 I15  ( .Vdd( VDD ), .In( X5 ), .GND( GND ), .Out( net51 ) );

INV    
 I14  ( .Vdd( VDD ), .In( X4 ), .GND( GND ), .Out( net33 ) );

INV    
 I11  ( .Vdd( VDD ), .In( X2 ), .GND( GND ), .Out( net35 ) );

INV    
 I10  ( .Vdd( VDD ), .In( X3 ), .GND( GND ), .Out( net34 ) );

INV    
 I5  ( .Vdd( VDD ), .In( X1 ), .GND( GND ), .Out( net36 ) );

INV    
 I0  ( .Vdd( VDD ), .In( X0 ), .GND( GND ), .Out( net37 ) );

MUX    
 I12  ( .Vdd( VDD ), .Sel( X5 ), .In1( X4 ), .In0( net33 ), .GND( GND ), .Out( net38 ), .SelBar( net51 ) );

MUX    
 I8  ( .Vdd( VDD ), .Sel( X5 ), .In1( X3 ), .In0( net34 ), .GND( GND ), .Out( net39 ), .SelBar( net51 ) );

MUX    
 I6  ( .Vdd( VDD ), .Sel( X5 ), .In1( X2 ), .In0( net35 ), .GND( GND ), .Out( net40 ), .SelBar( net51 ) );

MUX    
 I3  ( .Vdd( VDD ), .Sel( X5 ), .In1( X1 ), .In0( net36 ), .GND( GND ), .Out( net41 ), .SelBar( net51 ) );

MUX    
 I1  ( .Vdd( VDD ), .Sel( X5 ), .In1( X0 ), .In0( net37 ), .GND( GND ), .Out( net42 ), .SelBar( net51 ) );

MIRROR_CARRYOUT_ONLY    
 I13  ( .Cin( net043 ), .Vdd( VDD ), .X_i( net38 ), .GND( GND ), .Th_i( T4 ), .Out( OUT ) );

MIRROR_CARRYOUT_ONLY    
 I9  ( .Cin( net044 ), .Vdd( VDD ), .X_i( net39 ), .GND( GND ), .Th_i( T3 ), .Out( net43 ) );

MIRROR_CARRYOUT_ONLY    
 I7  ( .Cin( net045 ), .Vdd( VDD ), .X_i( net40 ), .GND( GND ), .Th_i( T2 ), .Out( net44 ) );

MIRROR_CARRYOUT_ONLY    
 I4  ( .Cin( net046 ), .Vdd( VDD ), .X_i( net41 ), .GND( GND ), .Th_i( T1 ), .Out( net45 ) );

MIRROR_CARRYOUT_ONLY    
 I2  ( .Cin( net51 ), .Vdd( VDD ), .X_i( net42 ), .GND( GND ), .Th_i( T0 ), .Out( net46 ) );

endmodule

