// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module Master (
);
wire net29;
wire net035;
wire net024;
wire net022;
wire net052;
wire net032;
wire net041;
wire net047;
wire net043;
wire net27;
wire net028;
wire net057;
wire net3;
wire net038;
wire net040;
wire net030;
wire net034;
wire net036;
wire net17;
wire net23;
wire net046;
wire net053;
wire net042;
wire net051;
wire net24;
wire net21;
wire net28;
wire net13;
wire net045;
wire net9;
wire net11;
wire net050;
wire net026;
wire net044;
wire net023;
wire net5;
wire net020;
wire net10;
wire net30;
wire net20;

MIRROR_CARRYOUT_ONLY    
 I4  ( .Cin( net9 ), .Vdd( net20 ), .X_i( net022 ), .GND( net13 ), .Th_i( net5 ), .Out( net3 ) );

MIRROR_CARRYOUT_ONLY    
 I3  ( .Cin( net10 ), .Vdd( net20 ), .X_i( net028 ), .GND( net13 ), .Th_i( net11 ), .Out( net9 ) );

MIRROR_CARRYOUT_ONLY    
 I2  ( .Cin( net21 ), .Vdd( net20 ), .X_i( net034 ), .GND( net13 ), .Th_i( net17 ), .Out( net10 ) );

MIRROR_CARRYOUT_ONLY    
 I1  ( .Cin( net27 ), .Vdd( net20 ), .X_i( net24 ), .GND( net13 ), .Th_i( net23 ), .Out( net21 ) );

MIRROR_CARRYOUT_ONLY    
 I0  ( .Cin( net28 ), .Vdd( net20 ), .X_i( net30 ), .GND( net13 ), .Th_i( net29 ), .Out( net27 ) );

MUX    
 I9  ( .Vdd( net20 ), .Sel( net020 ), .In1( net024 ), .In0( net023 ), .GND( net13 ), .Out( net022 ) );

MUX    
 I8  ( .Vdd( net20 ), .Sel( net026 ), .In1( net030 ), .In0( net057 ), .GND( net13 ), .Out( net028 ) );

MUX    
 I7  ( .Vdd( net20 ), .Sel( net032 ), .In1( net036 ), .In0( net035 ), .GND( net13 ), .Out( net034 ) );

MUX    
 I6  ( .Vdd( net20 ), .Sel( net038 ), .In1( net041 ), .In0( net040 ), .GND( net13 ), .Out( net24 ) );

MUX    
 I5  ( .Vdd( net20 ), .Sel( net043 ), .In1( net046 ), .In0( net045 ), .GND( net13 ), .Out( net30 ) );

INV    
 I14  ( .Vdd( net20 ), .In( net051 ), .GND( net13 ), .Out( net023 ) );

INV    
 I13  ( .Vdd( net20 ), .In( net042 ), .GND( net13 ), .Out( net057 ) );

INV    
 I12  ( .Vdd( net20 ), .In( net050 ), .GND( net13 ), .Out( net035 ) );

INV    
 I11  ( .Vdd( net20 ), .In( net053 ), .GND( net044 ), .Out( net040 ) );

INV    
 I10  ( .Vdd( net20 ), .In( net047 ), .GND( net052 ), .Out( net045 ) );

endmodule

